[global]
username = "lnconnu"
password_cmd = "pass spotify/lnconnu"

device_name = "spotifyd"
device_type = "computer"

bitrate = 320
volume_normalisation = true
normalisation_pregain = -10

backend = "pulseaudio"
